env:
  global:
    - CC_TEST_REPORTER_ID=87b1162308daedaad351c279c926ff8c7ecb94dcd54185b9e781477dc1eaa4db
language: python
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  python -m pytest -s
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT